language: php
cache:
  directories:
    - $HOME/.composer/cache/files

services:
  - mysql

php:
  - 7.2
  - 7.3

env:
  - SYMFONY_REQUIRE="4.4.*"
  - SYMFONY_REQUIRE="5.2.*"
  - PHPUNIT_VERSION="8.*"

matrix:
  include:
    - php: 7.3
      env:
        - TEST_COVERAGE=true
    - php: 7.1
      env:
        - PHPUNIT_VERSION="7.*"
        - SYMFONY_REQUIRE="4.4.*"
    - php: 7.4
      env:
        - COMPOSER_OPTIONS="--prefer-lowest"
    - php: 7.4
      env:
        - SYMFONY_REQUIRE="5.2.*"
        - PHPUNIT_VERSION="9.*"
    - php: 8.0
      env:
        - SYMFONY_REQUIRE="6.0.*"
        - PHPUNIT_VERSION="9.*"
        - STABILITY="dev"
    - php: 8.0
      env:
        - SYMFONY_REQUIRE="5.2.*"
        - PHPUNIT_VERSION="9.*"
        - SKIP_CS_FIXER=1

before_install:
  - phpenv config-rm xdebug.ini || echo "xDebug not disabled"
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex
  - |
      # inspired by Symfony's tfold helper, folds the output of successful commands
      tfold () {
          local title="$1"
          local fold=$(echo $title | sed -r 's/[^-_A-Za-z0-9]+/./g')
          shift
          echo -e "travis_fold:start:$fold"
          echo -e "\\e[1;34m$title\\e[0m"

          bash -xc "$*" 2>&1

          local ok=$?
          (exit $ok) && echo -e "travis_fold:end:$fold"
          (exit $ok)
      }
      export -f tfold

install:
  - rm -rf composer.lock vendor/*
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - composer require phpunit/phpunit:${PHPUNIT_VERSION:-"8.*"} --update-with-all-dependencies ${COMPOSER_OPTIONS}

before_script:
  - cp tests/Functional/app/parameters.yml.dist tests/Functional/app/parameters.yml
  - rm -rf tests/Functional/cache

script:
  - if [[ ${SKIP_CS_FIXER} != "1" ]]; then tfold 'PHP CS Fixer' make php_cs_fixer_check; fi
  - tfold 'PHPStan' make phpstan
  - |
    if [[ ${PHPUNIT_VERSION} == "7.*" ]]; then tfold 'PHPUnit 7' vendor/bin/phpunit -c tests/phpunit7.xml tests/;
    else tfold 'PHPUnit' vendor/bin/phpunit -c tests/ tests/;
    fi
  - tfold 'Behat' vendor/bin/behat -c tests/behat.yml -fprogress
