name: Build

on: [ pull_request ]

jobs:
    tests:
        runs-on: ubuntu-latest
        name: Test
        env:
            SYMFONY_REQUIRE: "${{ matrix.symfony_require }}"
        services:
            mysql:
                image: mysql:8.4
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: true
                ports:
                    - 3306:3306
                options: --health-cmd "mysqladmin ping --silent"
        strategy:
            fail-fast: false
            matrix:
                include:
                    -   php: 8.1
                        composer_flags: --prefer-lowest
                    -   php: 8.2
                    -   php: 8.3
                    -   php: 8.4

        steps:
            -   uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    coverage: none

            -   name: Configure Composer minimum stability
                if: matrix.stability
                run: composer config minimum-stability ${{ matrix.stability }}

            -   name: Remove CS fixer
                run: composer remove friendsofphp/php-cs-fixer --no-update --dev

            -   name: Install symfony/flex
                run: composer global config allow-plugins.symfony/flex true && composer global require symfony/flex

            -   name: Install dependencies
                run: composer update ${{ matrix.composer_flags }} --prefer-dist

            -   name: Phpunit
                run: make test

            -   name: Behat
                run: make behat

    php-stan:
        runs-on: ubuntu-latest
        name: php-stan

        steps:
            -   uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "8.4"

            -   name: Install dependencies
                run: composer update --prefer-dist

            -   name: PHPStan
                run: make phpstan

    cs-fixer:
        runs-on: ubuntu-latest
        name: CS-Fixer

        steps:
            -   uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "8.4"

            -   name: Install dependencies
                run: composer update --prefer-dist

            -   name: PHP CS Fixer
                run: make php_cs_fixer_check
